version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MANAGER_KEY_OTP: ${MANAGER_KEY}
      DECRYPT_KEY: ${DECRYPT_KEY}
      TZ: Europe/Madrid
    ports:
      - "80:80"
    volumes:
      - ./api/run.py:/back-api/run.py
      - ./api/app:/back-api/app
      - ./system_public_key.pem:/back-api/system_public_key.pem
    depends_on:
      db:
        condition: service_healthy
    networks:
      ElectXChain_network:
        aliases:
          - "api_host"

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_electionxchain
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data_db:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      ElectXChain_network:
        aliases:
          - "db_host"

networks: 
  ElectXChain_network:
    name: Elect_net 
    driver: bridge 
    ipam: 
      driver: default

volumes:
  data_db:

